"""empty message

Revision ID: ca0d7f0e0c7a
Revises: 
Create Date: 2024-03-11 17:27:36.432044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0d7f0e0c7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_tasks',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), server_default='now()', nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_done', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.CheckConstraint('end_date > start_date'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_users')
    op.drop_table('bot_tasks')
    # ### end Alembic commands ###
